### PR TITLE
Fix 404 irma router

### LINKED ISSUE #90: IRMA mount not working
After upgrading IRMA from 0.4.1 to 0.5.1 all the irmaclient paths return a 404.

### PR DESCRIPTION
**Pull request by stevenvegt**
fixes #90

### CODE REVIEW

File: engine/engine.go [hunk 1]
```diff
@@ -41,7 +44,18 @@ func NewAuthEngine() *nutsGo.Engine {
...
+			rewriteFunc := func(w http.ResponseWriter, r *http.Request) {
+				if strings.HasPrefix(r.URL.Path, prefix) {
+					// strip the prefix
+					r.URL.Path = strings.Split(r.URL.Path, prefix)[1]
+				}
+				authBackend.IrmaServer.HandlerFunc()(w, r)
+			}
+			// wrap the http handler in a echo handler
+			irmaEchoHandler := echo.WrapHandler(http.HandlerFunc(rewriteFunc))
 			routerWithAny.Any("/auth/irmaclient/*", irmaEchoHandler)
```
Comment (woutslakhorst) [inline engine/engine.go:59]: Ahhh I see, nasty....

Is there an option to add a test? So when either Irma or Chi changes something to the relative routing, we would know easily?

Comment (stevenvegt) [reply engine/engine.go]: Added 👍
